---
title: 'Lab-WA 1 - Graphing Data (Part 1)'
author: "Student Name"
date: "01/01/2000"
output: 
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# Lab Manual Practice

Copy and paste your work by following each example from the lab manual for this exercise. 

Only copy and paste the necessary code blocks, not the entire lab manual. 

When needed, add your text and/or extra code for your submission.

# Lab Exercise and Writing Assignment

The following generalization exercise and writing assignment is also in your lab R Markdown document for Lab 1. Complete your work in that document before the deadline.

## Lab Exercise (40 points)

Use the code from above to attempt to solve the extra things we ask you do for this assignment. Yours exercises are as follows:

1. Load the data set called NYC_Greenthumb_Community_Gardens.csv that is in the folder for this lab.(5 points)

For the rest of this exercise, be sure to rename any variable, if needed, to properly identify the contents of the data.

2. Use some of the R functions to examine the data set about the NYC's Community  Gardens to find out what are the variables in it. (5 points)

3. Make a graph plotting the number of community gardens per borough.  (10 points)

4. Now that you know which borough has the most of the community gardens in NYC, make a graph plotting the number of community gardens per neighborhood in that specific borough. (10 points)

  **Hint:** You will need to group your data by the variable whose values are the neighborhoods and filter the data by the variable that has the specific value equals to the borough.

## Writing Assignment (30 points)

Based on the results obtained above, answer the following:

1. Briefly describe what information we may find  about the NYC's Community  Gardens in the data set. For example, how big is the data set and give examples of some of the variables included and what they represent. (10 points)

2. According to your graph, in which borough most of the community gardens are located? (10 points)

3. Consider the borough you found to contains the most community gardens. What is the neighborhood in that borough with most of the gardens in it? (10 points)
